---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argocd-k3s-cert
spec:
  commonName: argocd.k3s.danmanners.io
  secretName: argocd-k3s-cert
  dnsNames:
    - argocd.k3s.danmanners.io
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.k3s.danmanners.io`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: argocd-k3s-cert
